services:
  nginx:
    build: docker/nginx
    volumes:
      - ./docker/nginx/sites-available:/etc/nginx/sites-available
      - ./docker/nginx/core:/etc/nginx/conf.d
      - ./:/var/www/
      - ./docker/nginx/logs:/var/log/nginxd
    ports:
      - 8876:80
    depends_on:
      - app
    links:
      - app
    container_name: project_nginx

  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./:/var/www
    depends_on:
      - db
    container_name: project_app

  db:
    image: mysql:8.0
    restart: always
    volumes:
      - ./tmp/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: optimize-db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 8101:3306
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    container_name: project_db
